import { Client } from "../client";
import { Config } from '../../index';
import { TxFee } from "../transaction";
export declare class TronClient extends Client {
    protected rpcUrl: string;
    protected tronWeb: any;
    protected address: string;
    private tokenContracts;
    private poolContracts;
    private ddContracts;
    private chainId;
    private energyFee;
    private tokenSymbols;
    private tokenDecimals;
    private ddContractAddresses;
    constructor(rpc: string, privateKey: string, config: Config);
    haltClient(): void;
    protected getTokenContract(tokenAddres: string): Promise<any>;
    protected getPoolContract(poolAddres: string): Promise<any>;
    protected getDdContract(ddQueueAddress: string): Promise<any>;
    getChainId(): Promise<number>;
    getTokenName(tokenAddress: string): Promise<string>;
    decimals(tokenAddress: string): Promise<number>;
    baseUnit(): string;
    toBaseUnit(humanAmount: string): string;
    fromBaseUnit(baseAmount: string): string;
    toBaseTokenUnit(tokenAddress: string, humanAmount: string): Promise<string>;
    fromBaseTokenUnit(tokenAddress: string, baseAmount: string): Promise<string>;
    getAddress(): Promise<string>;
    getBalance(): Promise<string>;
    getTokenBalance(tokenAddress: string): Promise<string>;
    getTokenNonce(tokenAddress: string): Promise<string>;
    allowance(tokenAddress: string, spender: string): Promise<bigint>;
    estimateTxFee(): Promise<TxFee>;
    sendTransaction(to: string, amount: bigint, data: string, selector: string): Promise<string>;
    transfer(to: string, amount: string): Promise<string>;
    transferToken(tokenAddress: string, to: string, amount: string): Promise<string>;
    approve(tokenAddress: string, spender: string, amount: string): Promise<string>;
    increaseAllowance(tokenAddress: string, spender: string, additionalAmount: string): Promise<string>;
    sign(data: string): Promise<string>;
    signTypedData(data: any): Promise<string>;
    getDirectDepositContract(poolAddress: string): Promise<string>;
    directDeposit(poolAddress: string, amount: string, zkAddress: string): Promise<string>;
    private truncateHexPrefix;
    private addHexPrefix;
    private fetchChainIdFrom;
    private getEnergyCost;
    private getAccountEnergy;
    private verifyAndSendTx;
}
